### PR TITLE
Setuptools - refactor the setup.py code

### PR DESCRIPTION
**Pull request by thomasleveil**
- add a `clean` command to setup.py
- extend the `build_exe` command to include the code producing the zip and installer files for win32
- move the InnoSetup assets files to the new `installer` directory to avoid messing up those files with builds temporary files
- rename pip-requires.txt to requirements.txt
- create build-requirements.txt

### CODE REVIEW

**Comment by danielepantaleone** [comment]
:+1: very nice improvements :+1:

**Comment by danielepantaleone** [comment]
Are there any reasons behind the removal or the `gztar` format for the source distribution? I added it because on some Linux distributions (eg Debian Wheezy) the zip/unzip command is not build-in and needs to be installed using `apt-get` while tarball and compressed tarball archives can be handled natively.

**Comment by thomasleveil** [comment]
the reason for gztar is because while the tar file within the gztar one is fine, the gztar file would embedded the full directory tree from the "C:\". This is either a bug in the sdist command or caveat on windows. Or maybe there is a setting for that but could not find it

**Comment by danielepantaleone** [comment]
On my Windows it was working fine. I tested all the distributions yesterday (except for the .egg one). But still, it's not a must :smile:

**Pull request merged**
